services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: kalpi_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
volumes:
  db_data:
